doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
        driver: pdo_mysql
        server_version: '8.0.41'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: TeleBot\Doctrine\PluralUnderscoreNamingStrategy
        auto_mapping: true
        mappings:
            TeleBot:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'TeleBot\Entity'
                alias: TeleBot
