monolog:
    handlers:
        main:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%/out.log'
            level: debug
            formatter: 'monolog.formatter.json'
            max_files: 10
