security:
    providers:
        auto_notes_provider:
            id: TeleBot\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/
            logout:
                path: logout
                target: /
            custom_authenticators:
                - TeleBot\Security\Authenticator\GrpcAuthenticator

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS, requires_channel: https }
        - { path: ^/webhook, roles: PUBLIC_ACCESS, requires_channel: https }
        - { path: ^/dashboard, roles: ROLE_USER, requires_channel: https }
        - { path: ^/, roles: PUBLIC_ACCESS, requires_channel: https }
