services:
    telebot:
        build:
            context: ./docker/web
            # dockerfile: prod/Dockerfile
            args:
                HOST_UID: ${HOST_UID}
        hostname: "telebot"
        container_name: "telebot"
        volumes:
            - .:/var/www/html
            - ./docker/web/apache.conf:/etc/apache2/sites-available/000-default.conf:ro
            - ${MIGRATIONS_PROJ}:/var/www/migrations
        tmpfs:
            - /tmp
        ports:
            - "8085:80"
        extra_hosts:
            - "database.lan:${DATABASE_IP}"
            - "auto-notes-server.lan:${GRPC_SERVER_IP}"

    nginx:
        build: ./docker/nginx
        volumes:
            - .:/var/www/html
        ports:
            - "443:443"
            - "80:80"
        depends_on:
            - telebot
        links:
            - telebot

networks:
    default:
        name: autonotes_net
