framework:
    secret: '%env(APP_SECRET)%'
    profiler: { only_exceptions: false }
    csrf_protection: true

    session:
        name: SESSID

    default_locale: '%locale%'
    translator:
        fallbacks:
            - '%locale%'
