parameters:
    locale: 'ru'
    grpc_url: '%env(GRPC_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $grpcUrl: '%grpc_url%'

    _instanceof:
        Xelbot\Telegram\Command\TelegramCommandInterface:
            tags:
                - { name: telegram-command }

    TeleBot\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/{DependencyInjection,Entity,Form,Utils,DTO}'
            - '../src/Security/User.php'

    TeleBot\Controller\WebHookController:
        arguments:
            $secretToken: '%env(BOT_WEBHOOK_TOKEN)%'

    TeleBot\EventListener\JsonBodyListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 10 }
    TeleBot\EventListener\TwirpErrorListener:
        tags:
            - { name: kernel.event_listener, method: 'onKernelException' }

    TeleBot\Form\Type\CostType: ~
    TeleBot\Form\Type\RpcEntityType: ~

    TeleBot\Service\TokenStorage:
        arguments:
            $secret: '%env(APP_SECRET)%'

    telebot.telegram_bot:
        class: Xelbot\Telegram\Robot
        arguments:
            - "%env(BOT_TOKEN)%"
            - "%env(int:BOT_ADMIN_ID)%"
        calls:
            - [ setLogger, [ "@monolog.logger" ]]

    Xelbot\Telegram\Robot: '@telebot.telegram_bot'
