parameters:
    locale: 'ru'
    grpc_url: '%env(GRPC_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $grpcUrl: '%grpc_url%'

    _instanceof:
        Xelbot\Telegram\Command\TelegramCommandInterface:
            tags:
                - { name: telegram-command }

    TeleBot\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/DependencyInjection'
            - '../src/Entity'
            - '../src/Form'
            - '../src/Security/User.php'

    telebot.telegram_bot:
        class: Xelbot\Telegram\Robot
        arguments:
            - "%env(BOT_TOKEN)%"
            - "%env(int:BOT_ADMIN_ID)%"
        calls:
            - [ setLogger, [ "@monolog.logger" ]]

    Xelbot\Telegram\Robot: '@telebot.telegram_bot'
